---

extends:
   - 'airbnb-base'
   - 'plugin:import/recommended'
   - 'eslint:recommended'
   
env:
   node: true
   browser: true
   
parser: babel-eslint

rules:
  no-console: 0
  
plugins:
  - import
